### ISSUE TITLE
Clear validation error

### ISSUE THREAD

**Issue by j-mary** [srtraj/dropdown_textfield#14]
Validation error does not clear after selecting a value from the dropdown list
<img width="309" alt="Screenshot 2022-11-20 at 4 58 39 AM" src="https://user-images.githubusercontent.com/25941404/202884712-94830dec-7163-4410-a927-b2eb4b470b81.png">

**Comment by srtraj** [comment]
Hi j-mary ,

I have added **autovalidateMode** option to dropdown_textfield.

You could see this feature in [dropdown_textfield: ^1.0.7](https://pub.dev/packages/dropdown_textfield)
