### ISSUE TITLE
Hover effect in dropdown list

### ISSUE THREAD

**Issue by mi1971** [srtraj/dropdown_textfield#16]
Awesome widget. Just a suggestion...on desktop/web etc, the dropdown list should display a hover effect as the mouse hovers each item (to show they are clickable). This is pretty standard on all dropdown menus and lists, and autocompletes etc. Normally it would be a very subtle light grey. Same as how the listview works when you hover an item.  I haven't looked at the code, but it may be a case of using an Inkwell instead of a Gesturedetector. Thank you!!

**Comment by mi1971** [comment]
Actually just looked at your code. You have an inkwell, but I think maybe the hover effect is not showing because it needs to be inside a material widget... same as this https://stackoverflow.com/questions/45424621/inkwell-not-showing-ripple-effect

**Comment by srtraj** [comment]
Sorry for the late reply,

Noted,will add in next release

Thanks!
