### ISSUE TITLE
Possibility for dark mode?

### ISSUE THREAD

**Issue by Ripul01** [srtraj/dropdown_textfield#19]
Hey @srtraj, love the plugin you've created.

I wanted to know if it's possible to change the background of the overlay when we switch to dark mode.

I'm currently using Flex_color_theme for theming and all the text changes automatically but the background of the overlay stays white. Here's a picture to better understand what I'm saying:

![image](https://user-images.githubusercontent.com/48410268/213132137-4103ecea-eb69-41bb-8f1a-50714b51164f.png)

It would be amazing if the overlay and the search box could use themeData to get their styles.

**Comment by MahdiForughi** [comment]
same issue here

**Comment by srtraj** [comment]
I apologize for the delay in my response. I was busy with some other things, Assure you that I am currently working on this issue. I will make sure to include it in the next release.

**Comment by srtraj** [comment]
@Ripul01 Thank you for the kind words and for using our plugin! We're glad to hear that you're enjoying it.

Regarding the background of the overlay when switching to dark mode, i apologize for the delay and assure you that the will fix this bug next release.

**Comment by srtraj** [comment]
Fixed in  [dropdown_textfield: ^1.0.8](https://pub.dev/packages/dropdown_textfield)

@Ripul01 now you can customize dropdownlist color like below
Example:
`dropdownColor: Colors.green,`
