### ISSUE TITLE
Hint text and button 'ok'

### ISSUE THREAD

**Issue by valientegaston** [srtraj/dropdown_textfield#2]
Hi! Excellent widget! Thank you! 
Can I change hint (Select Item) text?   
Is it possible to customize color and text of 'OK' button in multiselect?.

**Comment by srtraj** [comment]
> Hi! Excellent widget! Thank you! Can I change hint (Select Item) text? Is it possible to customize color and text of 'OK' button in multiselect?.

Thank you Valientegaston!,

**hint text** - you can change hint text by using textFieldDecoration as below

`  DropDownTextField(
               dropDownList: [
                    DropDownValueModel(name: 'name1', value: "value1"),
                    DropDownValueModel(name: 'name2', value: "value2"),
                    DropDownValueModel(name: 'name3', value: "value3"),
                  ],
                  **textFieldDecoration: InputDecoration(hintText: "custom hint text"),**
                ),`

**'OK' button in multiselect** - as of now you can't customize multiselect 'OK' button but i have noted this point, will definitely add in next version.

**Comment by valientegaston** [comment]
Thank you!

**Comment by srtraj** [comment]
https://pub.dev/packages/dropdown_textfield/versions/1.0.0

FYI..
new version of code published
Now you can change button text, color and textstyle

**Comment by srtraj** [comment]
> Thank you!


FYI..

[new version of code published ](https://pub.dev/packages/dropdown_textfield/versions/1.0.0)
Now you can change button text, color and textstyle
