### ISSUE TITLE
MultiSelection dropdown closes immediately on tap of checkbox

### ISSUE THREAD

**Issue by sharpsaravanan** [srtraj/dropdown_textfield#22]
MultiSelection dropdown closes immediately on tap of checkbox( unable to set checkbox state) after upgrading to flutter  stable version 3.7.0. 
code: [dropdown_textfield](https://github.com/srtraj/dropdown_textfield) example code

 flutter --version  
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (6 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

**Comment by sharpsaravanan** [comment]
_textFieldFocusNode.addListener(() {
      if (!_searchFocusNode.hasFocus &&
          !_textFieldFocusNode.hasFocus &&
                  _isExpanded) 

Modify _textFieldFocusNode.addListener(() as 

_textFieldFocusNode.addListener(() {
      if (!_searchFocusNode.hasFocus &&
          !_textFieldFocusNode.hasFocus &&
          !widget.isMultiSelection &&
          _isExpanded)

**Comment by acamenhas** [comment]
Same problem here

Flutter 3.7.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c07f788888 (6 days ago) • 2023-02-22 17:52:33 -0600
Engine • revision 0f359063c4
Tools • Dart 2.19.2 • DevTools 2.20.1
