### ISSUE TITLE
Error Ticker When Ticker is Show and We Click Back

### ISSUE THREAD

**Issue by curlylazy** [srtraj/dropdown_textfield#24]
hello,

i found a bug (maybe), when we click the dropdown, while the dropdown showing data, then click back to the previouse page, and suddenly its triggred an error..

`FlutterError (_DropDownTextFieldState#6aa21(tickers: tracking 1 ticker) was disposed with an active Ticker.`

![image](https://user-images.githubusercontent.com/7134650/220814229-42de0f18-1207-4620-9261-e18fb5f3e837.png)

hope you can help me..

**Comment by dankhan-helmet** [comment]
I'm getting the same error too.  I notice that the AnimationController isn't disposed in the dispose() function of the _DropDownTextFieldState class.  However disposing of this still has the same bug - I'm not quite sure how to remove the ticker before disposing.  Anyone?

``` line 476
@override
  void dispose() {
    if (widget.searchFocusNode == null) _searchFocusNode.dispose();
    if (widget.textFieldFocusNode == null) _textFieldFocusNode.dispose();
    _controller.dispose();  // <--- this added here
    _cnt.dispose();
    super.dispose();
  }
```

**Comment by srtraj** [comment]
Thank you for the fix, @dankhan-helmet. I have included it in the latest release. Sorry for delayed response, @curlylazy . I was bus with other things and couldn't maintain this package. The issue has been fixed in the latest release, dropdown_textfield: ^1.1.0

**Comment by curlylazy** [comment]
thank you so much for fixing the package.

**Comment by dankhan-helmet** [comment]
Awesome thanks so much for the fix.  Just to note that this update only supports flutter >= v3.22 only, due to `MaterialStateProperty` -> `WidgetStateProperty` [breaking changes](https://docs.flutter.dev/release/breaking-changes/material-state).
