### ISSUE TITLE
not allow rtl language in dropdown

### ISSUE THREAD

**Issue by MayHatuel** [srtraj/dropdown_textfield#29]
https://github.com/srtraj/dropdown_textfield/blob/1a24411cd04bd03c798bf355f5c7ee139c31185c/lib/dropdown_textfield.dart#LL1107C33-L1107C65

alignment: Alignment.centerLeft,

**Comment by srtraj** [comment]
@MayHatuel Sorry for delayed reply, I was busy with other things and couldn't maintain this package. Added alignment based on rtl . Please check the latest release: dropdown_textfield version 1.1.0
