### ISSUE TITLE
setState inside onChanged

### ISSUE THREAD

**Issue by valientegaston** [srtraj/dropdown_textfield#3]
Hi! I don't know if it's a widget bug or a misconception of mine, but if I call setState inside onchanged, the element name doesn't replace the hint text, but the widget shows a cross. Example code below. Thank you. 

`import 'package:dropdown_textfield/dropdown_textfield.dart';
import 'package:flutter/material.dart';

class Test2 extends StatefulWidget {
  Test2({Key? key}) : super(key: key);

  @override
  State<Test2> createState() => _Test2State();
}

class _Test2State extends State<Test2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DropDownTextField(
        dropDownList: [
          DropDownValueModel(name: 'name1', value: "value1"),
          DropDownValueModel(name: 'name2', value: "value2"),
          DropDownValueModel(name: 'name3', value: "value3"),
          DropDownValueModel(name: 'name4', value: "value4"),
          DropDownValueModel(name: 'name5', value: "value5"),
          DropDownValueModel(name: 'name6', value: "value6"),
        ],
        onChanged: (val) {
          setState(() {});
        },
      ),
    );
  }
}`

**Comment by srtraj** [comment]
Hi ,

Please add a controller ,if you want to rebuild the widget when the
dropdown item is selected.like below

  late SingleValueDropDownController _cnt;

  @override
  void initState() {
    _cnt = SingleValueDropDownController();
    super.initState();
  }

  @override
  void dispose() {
    _cnt.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: DropDownTextField(
          singleController: _cnt,
          dropDownList: [
            DropDownValueModel(name: 'name1', value: "value1"),
            DropDownValueModel(name: 'name2', value: "value2"),
            DropDownValueModel(name: 'name3', value: "value3"),
            DropDownValueModel(name: 'name4', value: "value4"),
            DropDownValueModel(name: 'name5', value: "value5"),
            DropDownValueModel(name: 'name6', value: "value6"),
          ],
          onChanged: (val) {
            setState(() {});
          },
        ),
      ),
    );
  }
}


Thanks and Regards,
Sharathraj A

**Comment by srtraj** [comment]
> Hi! I don't know if it's a widget bug or a misconception of mine, but if I call setState inside onchanged, the element name doesn't replace the hint text, but the widget shows a cross. Example code below. Thank you.
> 
> `import 'package:dropdown_textfield/dropdown_textfield.dart'; import 'package:flutter/material.dart';
> 
> class Test2 extends StatefulWidget { Test2({Key? key}) : super(key: key);
> 
> @OverRide State createState() => _Test2State(); }
> 
> class _Test2State extends State { @OverRide Widget build(BuildContext context) { return Scaffold( body: DropDownTextField( dropDownList: [ DropDownValueModel(name: 'name1', value: "value1"), DropDownValueModel(name: 'name2', value: "value2"), DropDownValueModel(name: 'name3', value: "value3"), DropDownValueModel(name: 'name4', value: "value4"), DropDownValueModel(name: 'name5', value: "value5"), DropDownValueModel(name: 'name6', value: "value6"), ], onChanged: (val) { setState(() {}); }, ), ); } }`

new version of code published 

> Hi! I don't know if it's a widget bug or a misconception of mine, but if I call setState inside onchanged, the element name doesn't replace the hint text, but the widget shows a cross. Example code below. Thank you.
> 
> `import 'package:dropdown_textfield/dropdown_textfield.dart'; import 'package:flutter/material.dart';
> 
> class Test2 extends StatefulWidget { Test2({Key? key}) : super(key: key);
> 
> @OverRide State createState() => _Test2State(); }
> 
> class _Test2State extends State { @OverRide Widget build(BuildContext context) { return Scaffold( body: DropDownTextField( dropDownList: [ DropDownValueModel(name: 'name1', value: "value1"), DropDownValueModel(name: 'name2', value: "value2"), DropDownValueModel(name: 'name3', value: "value3"), DropDownValueModel(name: 'name4', value: "value4"), DropDownValueModel(name: 'name5', value: "value5"), DropDownValueModel(name: 'name6', value: "value6"), ], onChanged: (val) { setState(() {}); }, ), ); } }`

FYI..

[new version of code published](https://pub.dev/packages/dropdown_textfield/versions/1.0.0)
Fixed setState bug in onChanged function,Now you can call setState without controller
