### ISSUE TITLE
Can the text field and the search field be combined?

### ISSUE THREAD

**Issue by Kimi-Arthur** [srtraj/dropdown_textfield#31]
It would be great if the text field is also the search field, ~otherwise after clicking the text field, the user needs to click again to actually start searching.~

I see there is a `searchAutofocus`, but visually it would be better if they are the same field.

It works even better when combined with #30.

Thanks!

**Comment by srtraj** [comment]
@Kimi-Arthur , you can enable search on the main textfield by setting readonly to false.
