### ISSUE TITLE
While Running Program getting error in subtitle1 isn't defined

### ISSUE THREAD

**Issue by postboxat18** [srtraj/dropdown_textfield#54]
Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:46: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
../../.pub-cache/hosted/pub.dev/dropdown_textfield-1.0.8/lib/dropdown_textfield.dart:453:64: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Downloads/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
          (widget.listTextStyle ?? Theme.of(context).textTheme.subtitle1)!;
                                                               ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dropdown_textfield-1.0.8/lib/tooltip_widget.dart:153:60: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Downloads/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                        style: Theme.of(context).textTheme.subtitle1,
                                                           ^^^^^^^^^
Failed to compile application.

**Comment by bahaahany-eg** [comment]
same error, any help is appreciated

**Comment by bahaahany-eg** [comment]
A temporary solution until the plugin has a new upgrade. replace subtitle1 with titleMedium

**Comment by srtraj** [comment]
Sorry friends, I was busy with other things and couldn't maintain this package. 
Please check the latest release dropdown_textfield: ^1.1.0
