### ISSUE TITLE
Just 2 more little things...

### ISSUE THREAD

**Issue by acamenhas** [srtraj/dropdown_textfield#8]
Hello, first of al:l great component, thank you!

Just 2 things that I missed: 

- the possibility to change the color of the clear/cross icon
- and the possibility to style the list checkboxes

This way we can better adapt to the color palette of our project.
 
Otherwise it's perfect, thank you!

**Comment by srtraj** [comment]
Hi @acamenhas 

I have published new version of [Dropdown_textfield](https://pub.dev/packages/dropdown_textfield) and added more customizable option in this version,

Hope this can help you solve the problem!
