### ISSUE TITLE
InitialValue in multiSelection

### ISSUE THREAD

**Issue by acamenhas** [srtraj/dropdown_textfield#9]
Hello,

I'm trying to put an initialValue in the multiSelection version:
`initialValue: const ["SVP", "Surf", "Teste"]`

And the output is:
![initialValue](https://user-images.githubusercontent.com/14015712/191555389-4015c272-c765-4a28-a9b6-a9177a0757bc.jpg)

The selections are not ok!

**Comment by srtraj** [comment]
Hi @acamenhas 

Sorry for the incovience,
I have published new version of `[Dropdown_textfield](https://pub.dev/packages/dropdown_textfield)` and fixed reported bug in this version ,

Please revert if any further queries.

**Comment by srtraj** [comment]
Hi @acamenhas

Sorry for the incovience,
I have published new version of [Dropdown_textfield](https://pub.dev/packages/dropdown_textfield) and fixed reported bug in this version ,

Please revert if any further queries.
